"""
PDF generation utilities for daily NLP/LLM research reports.
"""
from __future__ import annotations

import re
from pathlib import Path
from xml.sax.saxutils import escape

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer


def _normalise_inline_md(text: str) -> str:
    """Apply lightweight markdown cleanup before rendering paragraph text."""
    cleaned = text.replace("**", "").replace("`", "")
    cleaned = re.sub(r"\s+", " ", cleaned).strip()
    return escape(cleaned)


def _extract_report_meta(lines: list[str]) -> tuple[str, str]:
    title = "Daily NLP & LLM Research Digest"
    date_text = ""

    for line in lines:
        raw = line.strip()
        if raw.startswith("# ") and not title:
            title = raw[2:].strip()
        if raw.lower().startswith("date:"):
            date_text = raw.split(":", 1)[1].strip()
            break

    return title, date_text


def generate_pdf_report(report_markdown: str, output_path: str | Path) -> Path:
    """
    Convert a markdown-like report string to a clean PDF.

    Supported line patterns:
    - #, ##, ### headings
    - - bullet lines
    - plain paragraphs
    """
    out = Path(output_path)
    out.parent.mkdir(parents=True, exist_ok=True)

    doc = SimpleDocTemplate(
        str(out),
        pagesize=A4,
        leftMargin=16 * mm,
        rightMargin=16 * mm,
        topMargin=14 * mm,
        bottomMargin=14 * mm,
        title="NLP & LLM Daily Research Digest",
        author="OpenClaw AI Lab",
    )

    styles = getSampleStyleSheet()
    cover_title_style = ParagraphStyle(
        "CoverTitle",
        parent=styles["Title"],
        fontSize=24,
        leading=30,
        alignment=1,
        textColor=colors.HexColor("#0F172A"),
        spaceAfter=10,
    )
    cover_meta_style = ParagraphStyle(
        "CoverMeta",
        parent=styles["BodyText"],
        fontSize=11,
        leading=14,
        alignment=1,
        textColor=colors.HexColor("#334155"),
    )
    title_style = ParagraphStyle(
        "ReportTitle",
        parent=styles["Title"],
        fontSize=20,
        leading=24,
        textColor=colors.HexColor("#111827"),
        spaceAfter=8,
    )
    h1_style = ParagraphStyle("H1", parent=styles["Heading1"], fontSize=15, leading=18, spaceBefore=10)
    h2_style = ParagraphStyle("H2", parent=styles["Heading2"], fontSize=13, leading=16, spaceBefore=8)
    body_style = ParagraphStyle("Body", parent=styles["BodyText"], fontSize=10.5, leading=14)
    bullet_style = ParagraphStyle("Bullet", parent=body_style, leftIndent=12)

    lines = report_markdown.splitlines()
    report_title, report_date = _extract_report_meta(lines)

    story = [
        Spacer(1, 35),
        Paragraph(_normalise_inline_md(report_title), cover_title_style),
        Spacer(1, 8),
    ]
    if report_date:
        story.append(Paragraph(_normalise_inline_md(f"Date: {report_date}"), cover_meta_style))
        story.append(Spacer(1, 4))
    story.append(Paragraph("Generated by OpenClaw Research Automation", cover_meta_style))
    story.append(Spacer(1, 16))
    story.append(Paragraph("―" * 35, cover_meta_style))
    story.append(Spacer(1, 18))

    for idx, raw_line in enumerate(lines):
        line = raw_line.strip()
        if not line:
            story.append(Spacer(1, 6))
            continue

        # Skip duplicated header metadata because it's already on the cover section.
        if idx <= 3 and (line.startswith("# ") or line.lower().startswith("date:")):
            continue

        if line.startswith("# "):
            story.append(Paragraph(_normalise_inline_md(line[2:]), title_style))
            continue

        if line.startswith("## "):
            story.append(Paragraph(_normalise_inline_md(line[3:]), h1_style))
            continue

        if line.startswith("### "):
            story.append(Paragraph(_normalise_inline_md(line[4:]), h2_style))
            continue

        if line.startswith("- "):
            story.append(Paragraph(f"• {_normalise_inline_md(line[2:])}", bullet_style))
            continue

        safe_line = _normalise_inline_md(line)
        if safe_line:
            story.append(Paragraph(safe_line, body_style))

    if not story:
        story.append(Paragraph("No content generated.", body_style))

    doc.build(story)
    return out
